# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metaudio < Formula
  desc ""
  homepage "https://github.com/apolo96"
  version "0.0.1"

  on_macos do
    url "https://github.com/apolo96/metaudio/releases/download/v0.0.1/metaudio_Darwin_all.tar.gz"
    sha256 "fae2d69cab2b8dbb930e2c0bd0dfc8ddd2bd7377a15c97b6ae4c21826df3dd49"

    def install
      bin.install "metaudio"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/apolo96/metaudio/releases/download/v0.0.1/metaudio_Linux_x86_64.tar.gz"
      sha256 "845a5bcebae905bc2d6ee6ad8539d8930179a94330fd3e5ccb1d98775722b6eb"

      def install
        bin.install "metaudio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apolo96/metaudio/releases/download/v0.0.1/metaudio_Linux_arm64.tar.gz"
      sha256 "782b230b5673c2ad6a7d3cdbc514c9908ce4cbb4cdb1d912c47a676a0fee0af0"

      def install
        bin.install "metaudio"
      end
    end
  end
end
